---
- hosts: postgresql-servers
  become: true

  tasks:
    - name: Install PostgreSQL
      yum:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      become_user: postgres
      become_method: su
      command: initdb -D /var/lib/pgsql/data

    - name: Start PostgreSQL service
      systemd:
        name: postgresql
        state: started

    - name: Enable PostgreSQL service on boot
      systemd:
        name: postgresql
        enabled: true

    - name: Set PostgreSQL password for user postgres
      postgresql_user:
        db: postgres
        user: postgres
        password: "{{ postgres_password }}"

    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ postgres_db }}"
        owner: "{{ postgres_user }}"
        encoding: UTF8
        lc_collate: "en_US.UTF-8"
        lc_ctype: "en_US.UTF-8"

    - name: Configure PostgreSQL to listen on all interfaces
      lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^#?listen_addresses = .*'
        line: 'listen_addresses = '*''

    - name: Configure PostgreSQL authentication
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: 'host    all             all             0.0.0.0/0               md5'

    - name: Restart PostgreSQL service
      systemd:
        name: postgresql
        state: restarted
